#docker-compose.yml
services:
  web:
    image: ${DOCKER_USERNAME}/backend:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_HTTP_PORTS=5000
      - JWTSETTINGS__SECRETKEY=${JWTSETTINGS__SECRETKEY}
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=${DB_NAME};Username=${DB_USERNAME};Password=${DB_PASSWORD}
      - EMAILSETTINGS__SMTPPASS=${EMAILSETTINGS__SMTPPASS}
      - GOOGLESETTINGS__CLIENTID=${GOOGLESETTINGS__CLIENTID}
      - GOOGLESETTINGS__CLIENTSECRET=${GOOGLESETTINGS__CLIENTSECRET}
      - PAYMENTSETTINGS__APIKEY=${PAYMENTSETTINGS__APIKEY}
      - GEMINISETTINGS__APIKEY=${GEMINISETTINGS__APIKEY}
      - GOOGLE_APPLICATION_CREDENTIALS_JSON=${GOOGLE_APPLICATION_CREDENTIALS_JSON}
    # restart: always
