#docker-compose.yml
services:
  web:
    image: ${DOCKER_USERNAME}/backend:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Web/Dockerfile
#    depends_on:
#      mysql:
#        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - JWTSETTINGS__SECRETKEY=${JWTSETTINGS__SECRETKEY}
      - ConnectionStrings__DefaultConnection=Server=mysql;Port=3306;Database=${DB_NAME};Uid=${DB_USERNAME};Pwd=${DB_PASSWORD};Allow User Variables=true;
      - EMAILSETTINGS__SMTPPASS=${EMAILSETTINGS__SMTPPASS}
      - GOOGLESETTINGS__CLIENTID=${GOOGLESETTINGS__CLIENTID}
      - GOOGLESETTINGS__CLIENTSECRET=${GOOGLESETTINGS__CLIENTSECRET}
      - PAYMENTSETTINGS__APIKEY=${PAYMENTSETTINGS__APIKEY}
      - GEMINISETTINGS__APIKEY=${GEMINISETTINGS__APIKEY}
      - GOOGLE_APPLICATION_CREDENTIALS_JSON=${GOOGLE_APPLICATION_CREDENTIALS_JSON}
    # restart: always
    volumes:
#        - ./src/Web/wwwroot/uploads:/app/wwwroot/uploads
      - web_uploads:/app/wwwroot/uploads
volumes:
  web_uploads: