#docker-compose.db.yml
services:
  postgres:
    image: postgres:16.9
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5555:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    # restart: always
    deploy:
      resources:
        limits: 
          cpus: "3.0"
          memory: 3G

volumes:
  pgdata: