services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}   # root password
      - MYSQL_DATABASE=${DB_NAME}            # tên DB
      - MYSQL_USER=${DB_USERNAME}            # user
      - MYSQL_PASSWORD=${DB_PASSWORD}        # password cho user
    ports:
      - "3307:3306"   
    volumes:
      - mysqldata:/var/lib/mysql
    # restart: always
    deploy:
      resources:
        limits:
          cpus: "3.0"
          memory: 3G

volumes:
  mysqldata:
