
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Ijc3Nzc3Nzc3LTc3NzctNzc3Ny03Nzc3LTc3Nzc3Nzc3Nzc3NyIsImV4cCI6MTc4NzEyNzA1OCwiaXNzIjoiSXNzdWVyIiwiYXVkIjoiQXVkaWVuY2UifQ.OzeYQQnnH-EixON84iexsjPm_cfPBWO0kQLCL-xT6X0 
###
POST https://47db5a77fb93.ngrok-free.app/ask_user

{
  "uuid": "string",
  "question": "string"
}


### 
POST http://localhost:5000/api/Product/CreateOrUpdateProduct
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "productId": "61f0ffb7-97bc-4acd-a0f5-f2a423a0122c",
  "name": "Test",
  "description": "test",
  "imageUrl": "http://36.50.135.207:5000/uploads/e9527e40-6ed7-4961-824c-8325175b346b.png",
  "basePrice": 10000,
  "categoryId": "a3889c74-e136-4e5a-87cd-9c0c7c35c7ef",
  "options": [
    {
      "optionId": "e158e777-52a2-46d1-827c-3550f9c86e68",
      "name": "SIZE",
      "values": [
        {
          "optionValueId": "a6401d2a-a530-42dc-9d8b-18ec05c491ab",
          "value": "S",
          "imageUrl": []
        }
      ]
    },
    {
      "optionId": "f603255f-f9e4-4b01-95c1-2cb0b2e2c2ac",
      "name": "COLOR",
      "values": [
        {
          "optionValueId": null,
          "value": "Đỏ",
          "imageUrl": []
        }
      ]
    }
  ],
  "variants": [
    {
      "id": null,
      "sku": "TEST_ĐỎ_S",
      "price": 10000,
      "stock": 0,
      "optionValues": {
        "COLOR": "Đỏ",
        "SIZE": "S"
      }
    }
  ]
}


### 
GET http://36.50.135.207:5000/api/Order/admin/all?PageNumber=1&PageSize=10&PaymentStatus=ONLINE_PAYMENT_PAID
Content-Type: application/json
Authorization: Bearer {{token}}



###
GET http://localhost:5000/api/Users?PageNumber=1&PageSize=10
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET http://36.50.135.207:5000/api/ProductDesign/08de12b4-d762-4758-84b6-00e78881bd01
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET http://localhost:5000/api/Cart/item
Content-Type: application/json
Authorization: Bearer {{token}}


###
POST http://36.50.135.207:5000/api/ProductDesign/CreateOrUpdateProductDesign
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "productDesignId": null,
    "productId": "6c9273bf-3721-48bf-b683-76fe69197a97",
    "productOptionValueId": "92739e8f-655c-425b-b89a-74de815fda76",
    "name": "Thiết kế Áo Thun",
    "icons": [
        {
            "imageUrl": "http://36.50.135.207:5000/uploads/01967a1a-7415-443a-b8e1-726c43fbf75f.webp"
        }
    ],
    "templates": [
        {
            "templateId": "08de12b4-7bcb-4148-8f6e-37a9b34b0685",
            "designImageUrl": "http://36.50.135.207:5000/uploads/23332292-2567-45f1-a756-e43eaba4ade2.png"
        },
        {
            "templateId": "08de12b4-7bcb-4146-8f93-fcef445f0911",
            "designImageUrl": "http://36.50.135.207:5000/uploads/4771b232-0be9-4efb-b887-5d75130c732c.png"
        }
    ]
}
