
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Ijc3Nzc3Nzc3LTc3NzctNzc3Ny03Nzc3LTc3Nzc3Nzc3Nzc3NyIsImV4cCI6MTc4NzEyNzA1OCwiaXNzIjoiSXNzdWVyIiwiYXVkIjoiQXVkaWVuY2UifQ.OzeYQQnnH-EixON84iexsjPm_cfPBWO0kQLCL-xT6X0 
###
POST https://47db5a77fb93.ngrok-free.app/ask_user

{
  "uuid": "string",
  "question": "string"
}


### 
POST http://localhost:5000/api/Product/CreateOrUpdateProduct
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "productId": null,
  "name": "Test",
  "description": "test",
  "imageUrl": "http://36.50.135.207:5000/uploads/e9527e40-6ed7-4961-824c-8325175b346b.png",
  "basePrice": 10000,
  "categoryId": "558f9bc6-6a24-4774-9bec-f6eec868f6f8",
  "options": [
    {
      "optionId": null,
      "name": "SIZE",
      "values": [
        {
          "optionValueId": null,
          "value": "S",
          "imageUrl": []
        }
      ]
    },
    {
      "optionId": null,
      "name": "COLOR",
      "values": [
        {
          "optionValueId": null,
          "value": "Đỏ",
          "imageUrl": []
        }
      ]
    }
  ],
  "variants": [
    {
      "id": null,
      "sku": "TEST_ĐỎ_S",
      "price": 10000,
      "stock": 5,
      "optionValues": {
        "COLOR": "Đỏ",
        "SIZE": "S"
      }
    }
  ]
}


### 
GET http://localhost:5000/api/ProductDesign/Search?PageNumber=1&PageSize=10
Content-Type: application/json
Authorization: Bearer {{token}}



###
GET http://localhost:5000/api/Users?PageNumber=1&PageSize=10
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET http://36.50.135.207:5000/api/ProductDesign/08de12b4-d762-4758-84b6-00e78881bd01
Content-Type: application/json
Authorization: Bearer {{token}}


###
POST http://localhost:5000/api/Cart/itemByOption
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "productId": "6c9273bf-3721-48bf-b683-76fe69197a97",
  "productOptionValueIds": [
    "92739e8f-655c-425b-b89a-74de815fda76",
    "bafd7403-94e2-49ee-8c3e-c2831f95b1a8"
  ],
  "productDesignId": "08de1329-61d9-4bbc-848c-0ea8088e3fe0",
  "quantity": 1
}


###
POST http://36.50.135.207:5000/api/ProductDesign/CreateOrUpdateProductDesign
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "productDesignId": null,
    "productId": "6c9273bf-3721-48bf-b683-76fe69197a97",
    "productOptionValueId": "92739e8f-655c-425b-b89a-74de815fda76",
    "name": "Thiết kế Áo Thun",
    "icons": [
        {
            "imageUrl": "http://36.50.135.207:5000/uploads/01967a1a-7415-443a-b8e1-726c43fbf75f.webp"
        }
    ],
    "templates": [
        {
            "templateId": "08de12b4-7bcb-4148-8f6e-37a9b34b0685",
            "designImageUrl": "http://36.50.135.207:5000/uploads/23332292-2567-45f1-a756-e43eaba4ade2.png"
        },
        {
            "templateId": "08de12b4-7bcb-4146-8f93-fcef445f0911",
            "designImageUrl": "http://36.50.135.207:5000/uploads/4771b232-0be9-4efb-b887-5d75130c732c.png"
        }
    ]
}
