
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Ijc3Nzc3Nzc3LTc3NzctNzc3Ny03Nzc3LTc3Nzc3Nzc3Nzc3NyIsImV4cCI6MTc4NzEyNzA1OCwiaXNzIjoiSXNzdWVyIiwiYXVkIjoiQXVkaWVuY2UifQ.OzeYQQnnH-EixON84iexsjPm_cfPBWO0kQLCL-xT6X0 
###
POST https://47db5a77fb93.ngrok-free.app/ask_user

{
  "uuid": "string",
  "question": "string"
}


### 
POST http://localhost:5000/api/Product/CreateOrUpdateProduct
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "productId": "61f0ffb7-97bc-4acd-a0f5-f2a423a0122c",
  "name": "Test",
  "description": "test",
  "imageUrl": "http://36.50.135.207:5000/uploads/e9527e40-6ed7-4961-824c-8325175b346b.png",
  "basePrice": 10000,
  "categoryId": "a3889c74-e136-4e5a-87cd-9c0c7c35c7ef",
  "options": [
    {
      "optionId": "e158e777-52a2-46d1-827c-3550f9c86e68",
      "name": "SIZE",
      "values": [
        {
          "optionValueId": "a6401d2a-a530-42dc-9d8b-18ec05c491ab",
          "value": "S",
          "imageUrl": []
        }
      ]
    },
    {
      "optionId": "f603255f-f9e4-4b01-95c1-2cb0b2e2c2ac",
      "name": "COLOR",
      "values": [
        {
          "optionValueId": null,
          "value": "Đỏ",
          "imageUrl": []
        }
      ]
    }
  ],
  "variants": [
    {
      "id": null,
      "sku": "TEST_ĐỎ_S",
      "price": 10000,
      "stock": 0,
      "optionValues": {
        "COLOR": "Đỏ",
        "SIZE": "S"
      }
    }
  ]
}






{
  "errors": {},
  "validationErrors": {},
  "data": {
    "productId": "ad98fe82-b689-4910-9b6e-032965f47263",
    "name": "Áo phông",
    "description": "<Bổ sung require>",
    "imageUrl": "http://36.50.135.207:5000/uploads/f59e8a7d-30f1-40a3-a3fe-f928729dfb65.jpg",
    "basePrice": 500000,
    "category": {
      "categoryId": "052762ac-63ce-42a5-bad7-1cb352f553b2",
      "name": "Hello"
    },
    "options": [
      {
        "optionId": "1652f546-fbe5-4a9d-b5ee-b4eb05105be7",
        "name": "COLOR",
        "values": [
          {
            "optionValueId": "ab8d743f-17ae-4fce-ad53-82fc397c0d2d",
            "value": "Xanh",
            "images": [
              "http://36.50.135.207:5000/uploads/aafad46f-793a-4cdf-a2b8-b81ac4cd55eb.jpeg"
            ]
          },
          {
            "optionValueId": "f024a653-d425-43da-a131-59ca442bec8e",
            "value": "Be",
            "images": [
              "http://36.50.135.207:5000/uploads/5ab8b696-0104-4af7-bb72-93ebb008cf62.jpeg"
            ]
          }
        ]
      },
      {
        "optionId": "ed91506e-05ca-4451-ae7f-c691ee7453fa",
        "name": "SIZE",
        "values": [
          {
            "optionValueId": "10ef1da7-754f-425b-90d7-4135c9ceb04d",
            "value": "S",
            "images": []
          },
          {
            "optionValueId": "19fe9edf-a5cd-43af-9646-374d2bb02d7c",
            "value": "Hello",
            "images": []
          }
        ]
      }
    ],
    "variants": [
      {
        "variantId": "22e417c0-9bd9-48a1-8224-d2bc903dbe0d",
        "sku": "ÁOPHÔNG_BE_S",
        "price": 500000,
        "stock": 0,
        "optionValues": {
          "SIZE": "S",
          "COLOR": "Be"
        }
      },
      {
        "variantId": "7a676234-a674-4b06-9cb5-1fc0b573f063",
        "sku": "AO_PHONG_XANH_HELLO",
        "price": 500000,
        "stock": 0,
        "optionValues": {
          "SIZE": "Hello",
          "COLOR": "Xanh"
        }
      },
      {
        "variantId": "9e3c7537-bd81-4bb5-8474-5e4c1ece0ee4",
        "sku": "AO_PHONG_BE_HELLO",
        "price": 500000,
        "stock": 0,
        "optionValues": {
          "SIZE": "Hello",
          "COLOR": "Be"
        }
      },
      {
        "variantId": "c50483f0-68cd-479a-bc33-ad04004ad558",
        "sku": "ÁOPHÔNG_XANH_S",
        "price": 500000,
        "stock": 0,
        "optionValues": {
          "SIZE": "S",
          "COLOR": "Xanh"
        }
      }
    ]
  },
  "success": true
}

